#!/usr/bin/env node
'use strict';

/**
 * task-parser.js — extrai estrutura de cada task.md e gera fichas + regista no process-registry
 * Story PM-4.2 — spec FEAT-03
 */

const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '../../..');
const TASKS_DIR  = path.join(ROOT, '.aiox-core', 'development', 'tasks');
const FILES_DIR  = path.join(ROOT, 'docs', 'process-maps', 'files');
const REGISTRY   = path.join(ROOT, 'squads', 'process-mapper', 'data', 'process-registry.yaml');

function esc(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

function parseTaskMd(content, filename) {
  const lines = content.split('\n');
  const result = { name: filename.replace('.md',''), agent: '', description: '', inputs: [], outputs: [], steps: [] };

  for (const line of lines) {
    if (line.startsWith('# ') && !result.title) result.title = line.replace(/^#\s+/,'').trim();
    if (/^agent:/i.test(line)) result.agent = line.replace(/^agent:\s*/i,'').trim();
    if (/^description:|^purpose:/i.test(line)) result.description = line.replace(/^(description|purpose):\s*/i,'').trim();
    if (/^\s*[-*]\s+input/i.test(line)) result.inputs.push(line.replace(/^\s*[-*]\s+(input[s]?:?\s*)?/i,'').trim());
    if (/^\s*[-*]\s+output/i.test(line)) result.outputs.push(line.replace(/^\s*[-*]\s+(output[s]?:?\s*)?/i,'').trim());
    if (/^##\s+step/i.test(line)) result.steps.push(line.replace(/^##\s+/,'').trim());
  }
  result.title = result.title || result.name;
  return result;
}

function taskCard(t) {
  const agent = t.agent ? `<div class="task-agent">${esc(t.agent)}</div>` : '';
  const desc  = t.description ? `<div class="task-desc">${esc(t.description.slice(0,200))}</div>` : '';
  return `
<div class="task-card" id="task-${esc(t.name)}">
  <div class="task-name">${esc(t.title || t.name)}</div>
  ${agent}${desc}
  <code class="task-file">${esc(t.name)}.md</code>
</div>`;
}

function generateIndexHTML(tasks) {
  const cards = tasks.map(taskCard).join('');
  return `<!DOCTYPE html>
<html lang="pt">
<head>
<meta charset="UTF-8">
<title>AIOX Task Dictionary</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Inter','Segoe UI',sans-serif;background:#0D0F14;color:#E8EAF0;padding:32px 20px}
h1{text-align:center;font-size:18px;font-weight:700;color:#A78BFA;margin-bottom:6px;letter-spacing:.06em;text-transform:uppercase}
.meta{text-align:center;font-size:12px;color:#6B7280;margin-bottom:28px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;max-width:1200px;margin:0 auto}
.task-card{background:#0F1117;border:1px solid rgba(255,255,255,.07);border-radius:8px;padding:12px;cursor:default}
.task-name{font-size:12px;font-weight:700;color:#C4B5FD;margin-bottom:4px}
.task-agent{font-size:10px;color:#38BDF8;margin-bottom:4px}
.task-desc{font-size:10px;color:#9CA3AF;margin-bottom:6px;line-height:1.4}
.task-file{font-size:9px;color:#4B5563;font-family:'Courier New',monospace}
</style>
</head>
<body>
<h1>AIOX Task Dictionary</h1>
<p class="meta">${tasks.length} tasks · fonte: .aiox-core/development/tasks/ · Story PM-4.2</p>
<div class="grid">${cards}</div>
</body>
</html>`;
}

function main() {
  if (!fs.existsSync(TASKS_DIR)) { console.error('tasks dir not found'); process.exit(1); }
  if (!fs.existsSync(FILES_DIR)) fs.mkdirSync(FILES_DIR, { recursive: true });

  const taskFiles = fs.readdirSync(TASKS_DIR)
    .filter(f => f.endsWith('.md') && !f.startsWith('README') && !f.startsWith('blocks'));

  const tasks = [];
  let parsed = 0, skipped = 0;

  for (const file of taskFiles) {
    try {
      const content = fs.readFileSync(path.join(TASKS_DIR, file), 'utf8');
      tasks.push(parseTaskMd(content, file));
      parsed++;
    } catch { skipped++; }
  }

  const indexPath = path.join(FILES_DIR, 'task-index.html');
  fs.writeFileSync(indexPath, generateIndexHTML(tasks), 'utf8');

  // Append registry entries
  const newEntries = tasks.map(t =>
    `  - source_file: ".aiox-core/development/tasks/${t.name}.md"\n    maps_to: ["files/${t.name}"]\n    layer: L2`
  ).join('\n');

  let registry = fs.existsSync(REGISTRY) ? fs.readFileSync(REGISTRY, 'utf8') : '';
  if (!registry.includes('# tasks auto-generated')) {
    registry += `\n# tasks auto-generated by task-parser.js (${tasks.length} tasks)\n${newEntries}\n`;
    fs.writeFileSync(REGISTRY, registry, 'utf8');
  }

  console.log(`✓ Task Index  → ${indexPath} (${parsed} tasks, ${skipped} skipped)`);
  console.log(`✓ Registry   → updated with ${tasks.length} task entries`);
}

if (require.main === module) main();
module.exports = { parseTaskMd, generateIndexHTML };
